// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & Record<string, unknown>> | ((props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<unknown[]> | unknown[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingMetadata
  ) => Promise<unknown> | unknown
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingViewport
  ) => Promise<unknown> | unknown
  metadata?: unknown
  viewport?: unknown
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<unknown[]> | unknown[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingMetadata
  ) => Promise<unknown> | unknown
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingViewport
  ) => Promise<unknown> | unknown
  metadata?: unknown
  viewport?: unknown
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  // @ts-expect-error - Generated validation file, module resolution handled by Next.js
  type HandlerType = typeof import("../../app/page")
  type __Check = __IsExpected<HandlerType>
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  // @ts-expect-error - Generated validation file, module resolution handled by Next.js
  type HandlerType = typeof import("../../app/layout")
  type __Check = __IsExpected<HandlerType>
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  type __Unused = __Check
}
